# Uncomment the next line to define a global platform for your project
# platform :ios, '11.0'

target 'Weather' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Weather
  pod 'RxSwift', '6.0.0-rc.1'
  pod 'RxCocoa', '6.0.0-rc.1'
  pod 'Alamofire', '~> 5.2'

  target 'WeatherTests' do
    inherit! :search_paths
    # Pods for testing
    pod 'RxBlocking', '6.0.0-rc.1'
    pod 'RxTest', '6.0.0-rc.1'
  end

end
